### ISSUE TITLE
Release 0.3.3

### ISSUE THREAD

**Issue by pbugnion** [pbugnion/jupyterlab-sql#110]
The following are outstanding for release 0.3.3:

- [x] Fix error when the connection URL doesn't include a database with MySQL databases (PR #108 )
- [x] Basic support for views (PR #104 )
~- [ ] Clarify installation outside of virtual environments (PR #100)~
- [x] Bump handlebars version (PR #116 )
- [x] Formalise supported databases (PR #114 , issue #113)
- [x] Test against latest version of JupyterLab, and check status of JupyterLab 2.
- [x] Include contributors list (PR #115).
- [x] Visibility of CI (PRs #117 and #118 ).
- [x] Hygiene remaining issues.
- [x] Improvements to README (issues #119 and PR #121).

**Comment by pbugnion** [comment]
Released 0.3.3-rc1.

**Comment by pbugnion** [comment]
Released as 0.3.3.

Release notes available [here](https://github.com/pbugnion/jupyterlab-sql/releases/tag/0.3.3).

**Comment by salvatorelionetti** [comment]
Hi, I'm currently not able to use this beautiful plugin.
I've tried jupyter lab versions 2.1.5, 2.2.4, without luck.

Can you please share which version have you tried for this release?

Thanks

**Comment by salvatorelionetti** [comment]
Finally 2.0.0 works!
